### ISSUE TITLE
部分页面失效

### ISSUE THREAD

**Issue by swhoro** [YanxinTang/Tampermonkey#2]
经查是导航栏右侧div的class属性从原来的nav-con fr变为了nav-con，且ul的class从fr变为了nav-con-ul，部分页面属性已改，部分页面仍用旧属性。
旧版页面举例：https://www.bilibili.com/video/av71511816
新版页面举例：https://www.bilibili.com
问题已在greasyfork提出，怕看不到

**Comment by YanxinTang** [comment]
多谢提醒，会尽快修复

**Comment by YanxinTang** [comment]
已修复
